### ISSUE TITLE
Add support for `deployPercentage` in `store.publish` API

### ISSUE THREAD

**Issue by jakub-g** [fregante/chrome-webstore-upload#89]
The [publish endpoint](https://github.com/fregante/chrome-webstore-upload/blob/main/index.js#L10) supports [`deployPercentage`](https://developer.chrome.com/docs/webstore/api#parameters-publish) which could be useful for staged deploys.

<img width="973" alt="image" src="https://github.com/fregante/chrome-webstore-upload/assets/1437027/68fb9062-7f9a-4076-9f9f-83fe0aad2708">

**Comment by fregante** [comment]
PR welcome

**Comment by remdash** [comment]
Hello,

I am willing to make a PR for this change. I've already had a look a the code and the change looks straightforward. 

There is just a design decision to make.

Most of the method to call the API have token being a last parameter and I assume this is something to keep in order to maintain consistency. 

This leaves two options for the change to the publish method.

Either turning the first parameter to an object, it could look like this:
```js
 async publish({ target = 'default', deployPercentage }, token = this.fetchToken()) {...}
 ```
 Or adding a new parameter with a default value of null or undefined:
 ```js
 async publish(target = 'default', deployPercentage = null , token = this.fetchToken()) {...}
 ```
 
 I can make a first version of the PR based on the first option, let me know if you prefer the second one.

**Comment by remdash** [comment]
Here is the PR: https://github.com/fregante/chrome-webstore-upload/pull/91

**Comment by fregante** [comment]
There's actually a PR open here with the answer to that in my review: #90
